---
title: "README"
author: "Wilson Hernández"
date: "13/3/2021"
output: html_document
---

# Peer-graded Assignment:

## Getting and Cleaning Data Course Project

This repository is made for the purpose of the course "Getting and Cleaning Data Course Project". It contains all the necessary information to run the asked instructions.

## Used data set:
Human Activity Recognition Using Smartphones


## run_analysis.R
Prepares data and follows the 5-points instruction:
Before, the code downloads the data and unzips it.
1. Merges the training and the test sets to create one data set.
First, objects are created based on the data sets downloaded. They are properly transformed into txt files. The train and test datasets area finally merged using rbind.

2. Extracts only the measurements on the mean and standard deviation for each measurement. 
First, I select the correct variables using grep and then create the required subset.
Data sets used:
features.txt
X_train.txt
y_train.txt
subject_train.txt
X_test.txt
y_test.txt
subject_test.txt

3. Uses descriptive activity names to name the activities in the data set
I name the activities using the additional file specified.

4. Appropriately labels the data set with descriptive variable names. 
I rename variables using text keys.

5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
Finall, I collapse data using the dplyr package to produce a txt file.


## Files:
Codebook.md. Contains the information on all variables and modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.

## Tidyset.txt
Contains the final tidy data asked in former point 5.

The run_analysis.R file performs all the 5 required steps as described below:

1. Dow



## License:
The data used belongs to and was created by:

Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita. November 2012.
